name: 美股ETF-每只一个文件

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run ETF Crawler
        run: python run_etf_per_file.py
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: etf_data
          path: etf_data/
